CREATE TABLE TBL_MEMBER(
	NAME VARCHAR2(30),
	AGE NUMBER
);

CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(100),
	COLOR VARCHAR2(100),
	PRICE NUMBER,
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

DROP TABLE TBL_MEMBER;